image: s2shape/s2shape-test-harness:latest

stages:
  - build
  - test

variables:
  ORACLE_USER: system
  ORACLE_PASSWORD: oracle
  ORACLE_SID: XE
  ORACLE_HOST: oracle
  TZ: CET

before_script:
  - dotnet restore -s https://www.myget.org/F/s2/ -s https://api.nuget.org/v3/index.json

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  services:
    - name: s2shape/oracle-xe:11.2.0
      alias: oracle

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/OracleSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init OracleSupplyCollector "Data Source=$ORACLE_HOST:1521/$ORACLE_SID;User Id=$ORACLE_USER;Password=$ORACLE_PASSWORD;"
    - dotnet SupplyCollectorDataLoader.dll -xunit OracleSupplyCollector "Data Source=$ORACLE_HOST:1521/$ORACLE_SID;User Id=$ORACLE_USER;Password=$ORACLE_PASSWORD;"
    - cd $ROOT_PROJECT_PATH
    - dotnet test

load_test:
  stage: test
  services:
    - name: s2shape/oracle-xe:11.2.0
      alias: oracle

  script:
    - ROOT_PROJECT_PATH=$(pwd)
    - dotnet build
    - dotnet publish
    - cd $ROOT_PROJECT_PATH/OracleSupplyCollectorLoader/bin/Debug/netcoreapp2.2/publish
    - cp -f /SupplyCollectorDataLoader/SupplyCollectorDataLoader/bin/Debug/netcoreapp2.2/SupplyCollectorDataLoader.runtimeconfig.json .
    - dotnet SupplyCollectorDataLoader.dll -init OracleSupplyCollector "Data Source=$ORACLE_HOST:1521/$ORACLE_SID;User Id=$ORACLE_USER;Password=$ORACLE_PASSWORD;"
    - dotnet SupplyCollectorDataLoader.dll -xunit OracleSupplyCollector "Data Source=$ORACLE_HOST:1521/$ORACLE_SID;User Id=$ORACLE_USER;Password=$ORACLE_PASSWORD;"
    - dotnet SupplyCollectorDataLoader.dll -samples OracleSupplyCollector "Data Source=$ORACLE_HOST:1521/$ORACLE_SID;User Id=$ORACLE_USER;Password=$ORACLE_PASSWORD;" TestCollection Test1:int,Test2:string,Test3:bool,Test4:double,Test5 1000000
    - cd $ROOT_PROJECT_PATH/OracleSupplyCollectorTests/bin/Debug/netcoreapp2.2/publish
    - SupplyCollectorTestHarness
